version: '3.4'

services:
  o2sat:
    image: o2sat:dev
    build:
      args:
        source: obj/Docker/empty/
    volumes:
      - C:\Users\Dickson\source\repos\O2Sat\O2Sat:C:\inetpub\wwwroot
      - :C:\remote_debugger:ro
    entrypoint: cmd /c "start /B C:\\ServiceMonitor.exe w3svc & C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /timeout:2147483646"
    environment:
      - DEV_ENVIRONMENT=1
      - VBCSCOMPILER_TTL=604800

